title: Paul May
description: Test website
url: ""
baseurl: ""

markdown: kramdown
permalink: /blog/:title/

collections:
  posts:
    output: true

exclude:
  - .vscode/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post