title: Paul May
description: Paul May is a strategic designer and product innovator. This is his personal website.
url: ""
baseurl: ""

markdown: kramdown
# permalink: /blog/:title/

collections:
  posts:
    output: true

exclude:
  - .vscode/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post